version: "3.4"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
      - /ext-drive/data/minio:/data
    ports:
      - 8085:8085
      - 8086:8086
    environment:
      MINIO_ROOT_USER: <user>
      MINIO_ROOT_PASSWORD: <pass>
      MINIO_ACCESS_KEY: <accesskey>
      MINIO_SECRET_KEY: <secretkey>
    command: server /data --console-address ":8086" --address ":8085"
    networks:
      ioak-net:
        aliases:
          - minio.docker

networks:
  ioak-net:
    external: true
